---
- name: make docker
  hosts: localhost
  
  tasks:
    - name: make dockers
      docker_container:
        image: busybox
        command: sleep 1d
        name: "busy{{ item }}"
      with_sequence: count=3
      
    - name: add hosts
      add_host:
        name: "busy{{ item }}"
        groups: dockers
        ansible_connection: docker
      with_sequence: count=3
      
- name: hi from docker
  hosts: dockers
# since the dockers do not contain python, disable gather_facts
  gather_facts: False
  
  tasks:
    - name: ping
      raw: echo $HOSTNAME
