---
- name: configure web-app
  hosts: web
  vars: 
    repo: myrepo.com/repo.git
    version: 8
    
  tasks:
    - name: install ngnix
      debug:
        msg: "dnf install nginx"
        
    - name: ensure web directory
      debug:
        msg: "mkdir /webapp"
        
    - name: get content
      debug:
        msg: "git clone --branch {{ version }} {{ repo }} /webapp"
        
    - name: ngnix config
      debug:
        msg: "put nginx in place"
      notify: restart ngnix
      changed_when: true
    
    - name: ensure ngnix running
      debug:
        msg: "service ngnix start"
        
  handlers:
    - name: restart ngnix
      debug:
        msg: "service ngnix restart"
